kind: Secret
apiVersion: v1
metadata:
  name: dspa-data-connection
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: '-100'
    opendatahub.io/connection-type: s3
    openshift.io/display-name: dspa-data-connection
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: east-1
  AWS_S3_ENDPOINT: http://minio.object-datastore.svc.cluster.local:9000
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_S3_BUCKET: models
type: Opaque
